### ISSUE TITLE
Club/Maces stunlock

### ISSUE THREAD

**Issue by Gregormack** [Blackstone-SS13/BLACKSTONE#235]
This is getting ridiculous, no matter how proficient the character in any weaponry - 1 club/mace hit and you are stunlocked till you die.

There is no point in any other weaponry, this is the most effective one.

**Comment by YosemiteYam** [comment]
But then how will the friendly neighbourhood town watch BONK you on the head to disable you without killing you

**Comment by ATP-Engineer** [comment]
You mean, disable you THEN kill you. Thats typically what happens.

**Comment by Wintermote** [comment]
Perhaps, instead of a direct stun, we apply only the knock back + a dizzy effect that applies a slow, and if a mob gets enough of these dizzy effects stacked, THEN we consider a stun chance (mitigated by constitution). It could be stacked with such effects from other sources (e.g. beer, some spells and drugs (?) ) so that drunkards are easier to knock out.

I have to agree, maces are incredible right now, but I think it can be brought into balance with a minor tuneup like this rather than just removing the stun outright.

**Comment by Osmos123** [comment]
#289 

This one should alleviate the problem. Being knocked out for 300 seconds (5 min) is insta death sentence. 5 seconds gives some change to survive.

**Comment by ChungusGamer666** [comment]
mostly fixed, knockouts for maces were made less nutty and knockback will be changed soon
