### ISSUE TITLE
[BUG] Unexpected Behavior for Stone Spears on Back Slots

### ISSUE THREAD

**Issue by DirtTastesBad** [Blackstone-SS13/BLACKSTONE#616]
## Describe the bug
Stone spears don't fit on back slots (both left and right). As far as I'm aware, changes were made to past weapons that had a similar problem, so assuming this is simply an oversight rather than intentional (especially given that polearms are underutilized as is)

## Steps to Reproduce:
-Craft stone spear
-Try to put it on one of your back slots

## Additional context
Just in case, I was playing a nudist at the time. Doubt that this is source of the problem however given that I could still wear backpacks/stone axes on my back, just specifically not the stone spear (for peak caveman roleplay)

**Comment by Wintermote** [comment]
This is expected behaviour; there was a recent revision of a "QoL" that was more of a balance change.
Originally polearms couldn't fit on the back, and now we're back to that.

>the pr that added polearms on back was sneaky about it and labelled it a QoL, that shit is downright satanic and this PR will be merged to rectify that sin

_Originally posted by @ChungusGamer666 in https://github.com/Blackstone-SS13/BLACKSTONE/issues/552#issuecomment-2093927036_
