### ISSUE TITLE
[REQUEST] Remove priest being able to turn anyone into a spellcaster according to their patron

### ISSUE THREAD

**Issue by YosemiteYam** [Blackstone-SS13/BLACKSTONE#821]
## Is your feature request related to a problem? Please describe. 

Priest's recruit acolyte spell gives the person being recruited devotion and the ability to get all the spells of the patron they follow. There are currently rogues who spawn in, rush to the priest and ask to be recruited in order to cast invisibility and blindness since they chose their patron as Noc. Same shit with any other class that have zero magical ability somehow turning into mages after being recruited, warriors/pilgrims/beggars getting instaheal spells by getting recruited as acolytes/templars even though they shouldn't be able to actually cast anything.

## Describe the solution you'd like

Recruit by priest should just change your job title to signify your joining the church, not turn half the server into spellcasters. 

## Describe alternatives you've considered

GROGNAK THE HALF ORC BRUTALIZER goes up to priest, asks to become his templar or acolyte to BE A DEVOTED FOLLOWER OF DA CHURCH, priests recruits Grognak as templar. Grognak is still the same warrior he is but with the job title of Templar on examine, but cannot actually spam devotion spells all of a sudden since he was never trained or was apt/wise/intelligent enough to be a spellcaster

**Comment by wgtjunior743** [comment]
To say the truth it is quite strange that the priest can give the magical hability to use miracles to anyone but if the priest is dumb enough to make anyone an acolyte or templar just because yes, i would not mind if the king cutted his head off, but these days we do get a high amount of mind numbly priests doing dumb actions all the time.
Noc rogue is very annoying and they are not matthios follower, this could be fixed if you are a follower a god and a user of his power and you are going against what the god preeach, admins could smite and remove your miracle powers from you.

**Comment by ChungusGamer666** [comment]
will be done

**Comment by CVSthePharmacy** [comment]
> will be done

don't

**Comment by pilotmans** [comment]
I'd prefer if this wasn't the case, having invisibility whilst as the archivist is fun, and also as someone who prefers to farm with dendor to make it less painful.

**Comment by Xkallubar** [comment]
> will be done

do not

**Comment by YosemiteYam** [comment]
Powergamers weeping about not being able to get free spells to use in their adventurer fragging (ie, rdming someone at the inn)
